In [70]:
import pandas as pd 
import numpy as np 
import re

In [71]:
output_file_path = 'D:/Jupyter Notebook Project/Kaggle/IMDB Movies Indonesian/Data/Raw/imdb indonesia star clean.csv'
df = pd.read_csv(output_file_path, encoding='unicode_escape',sep=';')

In [72]:
df.head(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
0,Kisah Tanah Jawa: Merapi,2019,18+,Horror,43 min,"7,8",37,Faozan Rizal,Deva Mahenra,Joshua Suherman,Laura Basuki,Laura Theux
1,Negeri Dongeng,2017,SU,Documentary,98 min,"8,9",8,Anggi Frisca,NaN,NaN,NaN,NaN
2,Workingman's Death,2005,13+,Documentary,122 min,"7,9","1,757",Michael Glawogger,NaN,NaN,NaN,NaN
3,Magic Hour,2015,18+,"Comedy, Drama",96 min,"8,7",6,Asep Kusdinar,Dimas Anggara,Michelle Ziudith,Rizky Nazar,Nadya Arina
4,Jakarta Love Story,2015,13+,Romance,50 min,NaN,NaN,Vemmy Sagita,Irish Bella,Rezky Adhitya,Rionaldo Stockhorst,Mischa Chandrawinata
5,Homebound,2022,13+,"Documentary, Short",10 min,NaN,NaN,Ismail Fahmi Lubish,NaN,NaN,NaN,NaN
6,Cherrybelle: Chibi Chibi Burger,2012,13+,Drama,NaN,NaN,NaN,Akbar de Wighar,Cherly Yuliana Anggraini,Margareth Angelina,Brigitta Cynthia,Jessyca Stefani Auryn
7,RONG (Hole),2018,SU,"Short, Drama, Family",35 min,NaN,NaN,Sri Nugroho,NaN,NaN,NaN,NaN
8,Srimulat: Hil yang Mustahal - Babak Kedua,2022,SU,"Biography, Comedy, Drama",110 min,NaN,NaN,Fajar Nugros,NaN,NaN,NaN,NaN
9,Before You Eat,2022,18+,Documentary,96 min,NaN,NaN,Kasan Kurdi,NaN,NaN,NaN,NaN

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708 entries, 0 to 2707
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              2708 non-null   object
 1   Year               2708 non-null   int64
 2   Rated              2708 non-null   object
 3   Genre              2708 non-null   object
 4   Runtime (Minutes)  2558 non-null   object
 5   Rating             1575 non-null   object
 6   Votes              1575 non-null   object
 7   Director           2708 non-null   object
 8   Star 1             2470 non-null   object
 9   Star 2             2325 non-null   object
 10  Star 3             2140 non-null   object
 11  Star 4             1838 non-null   object
dtypes: int64(1), object(11)
memory usage: 254.0+ KB

In [74]:
df.isnull().sum()

Title                   0
Year                    0
Rated                   0
Genre                   0
Runtime (Minutes)     150
Rating               1133
Votes                1133
Director                0
Star 1                238
Star 2                383
Star 3                568
Star 4                870
dtype: int64

In [75]:
df.sample(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
739,Ivanna,2022,R,"Horror, Thriller",103 min,"6,7",319,Kimo Stamboel,Caitlin Halderman,Jovarel Callum,Junior Roberts,Shandy William
551,Susah Sinyal: The Series,2022,TV-14,"Comedy, Drama",36 min,"7,3",36,Bene Dion Rajagukguk,Arie Kriting,Asri Welas,Boris Bokir,Abdur Arsyad
1614,Rumah Kentang: The Beginning,2019,17+,"Drama, Horror, Mystery",102 min,"5,8",93,Rizal Mantovani,Luna Maya,Christian Sugiono,Jajang C. Noer,Epy Kusnandar
1195,Topeng Bramacorah dan Media Sosial,2021,13+,Comedy,93 min,"9,1",7,Rama DeRanau,Gerald Abdullah,Rama DeRanau,Ferly Halim,Rino Mangunsaputro
461,Terang Malam,2014,13+,Sci-Fi,42 min,NaN,NaN,Pandu Birantoro,Ananda Moechtar,Indra Birowo,Ernest Samudera,Naya Anindita
1364,Kuntilanak Kesurupan,2011,D,"Comedy, Horror",79 min,"2,4",24,Nayato Fio Nuala,Irish Bella,Sazha Carissa,Azis Gagap,Violenzia Jeanette
2694,Ada Apa dengan Pocong?,2011,13+,"Comedy, Horror",104 min,"5,3",31,Nayato Fio Nuala,Zacky Zimah,Joanna Alexandra,Dallas Pratama,Mpok Atiek
1468,Anak Ajaib,2008,13+,Comedy,NaN,NaN,NaN,Tjandra Warasto,Juan Bione Subiantoro,El Manik,Vanessa Hinkel,Keisha Ratuliu
1233,Malam,2013,13+,"Short, Horror",8 min,NaN,NaN,Dira Nararyya,Hanan Cinthya,Riris Marpaung,Sekar Rarasati,NaN
1731,Sara & Fei: Stadhuis Schandaal,2018,17+,Drama,91 min,NaN,NaN,Adisoerya Abdi,Michael Lie,Volland Volt,Anwar Fuady,Rowiena Umboh

In [76]:
df['Runtime (Minutes)'] = df['Runtime (Minutes)'].str.replace('min', '', regex=True)
df.head()

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
0,Kisah Tanah Jawa: Merapi,2019,18+,Horror,43,"7,8",37,Faozan Rizal,Deva Mahenra,Joshua Suherman,Laura Basuki,Laura Theux
1,Negeri Dongeng,2017,SU,Documentary,98,"8,9",8,Anggi Frisca,NaN,NaN,NaN,NaN
2,Workingman's Death,2005,13+,Documentary,122,"7,9","1,757",Michael Glawogger,NaN,NaN,NaN,NaN
3,Magic Hour,2015,18+,"Comedy, Drama",96,"8,7",6,Asep Kusdinar,Dimas Anggara,Michelle Ziudith,Rizky Nazar,Nadya Arina
4,Jakarta Love Story,2015,13+,Romance,50,NaN,NaN,Vemmy Sagita,Irish Bella,Rezky Adhitya,Rionaldo Stockhorst,Mischa Chandrawinata

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708 entries, 0 to 2707
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              2708 non-null   object
 1   Year               2708 non-null   int64
 2   Rated              2708 non-null   object
 3   Genre              2708 non-null   object
 4   Runtime (Minutes)  2558 non-null   object
 5   Rating             1575 non-null   object
 6   Votes              1575 non-null   object
 7   Director           2708 non-null   object
 8   Star 1             2470 non-null   object
 9   Star 2             2325 non-null   object
 10  Star 3             2140 non-null   object
 11  Star 4             1838 non-null   object
dtypes: int64(1), object(11)
memory usage: 254.0+ KB

In [78]:
df['Runtime (Minutes)'] = df['Runtime (Minutes)'].astype('float')

In [79]:
df['Runtime (Minutes)'].describe()

count    2558.000000
mean       66.535966
std        40.281034
min         1.000000
25%        20.000000
50%        83.000000
75%        98.000000
max       262.000000
Name: Runtime (Minutes), dtype: float64

In [80]:
df['Runtime (Minutes)'] = df['Runtime (Minutes)'].fillna(df['Runtime (Minutes)'].median())

In [81]:
df.isnull().sum()

Title                   0
Year                    0
Rated                   0
Genre                   0
Runtime (Minutes)       0
Rating               1133
Votes                1133
Director                0
Star 1                238
Star 2                383
Star 3                568
Star 4                870
dtype: int64

In [82]:
df['Runtime (Minutes)'] = df['Runtime (Minutes)'].astype('int')

In [83]:
df.head(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
0,Kisah Tanah Jawa: Merapi,2019,18+,Horror,43,"7,8",37,Faozan Rizal,Deva Mahenra,Joshua Suherman,Laura Basuki,Laura Theux
1,Negeri Dongeng,2017,SU,Documentary,98,"8,9",8,Anggi Frisca,NaN,NaN,NaN,NaN
2,Workingman's Death,2005,13+,Documentary,122,"7,9","1,757",Michael Glawogger,NaN,NaN,NaN,NaN
3,Magic Hour,2015,18+,"Comedy, Drama",96,"8,7",6,Asep Kusdinar,Dimas Anggara,Michelle Ziudith,Rizky Nazar,Nadya Arina
4,Jakarta Love Story,2015,13+,Romance,50,NaN,NaN,Vemmy Sagita,Irish Bella,Rezky Adhitya,Rionaldo Stockhorst,Mischa Chandrawinata
5,Homebound,2022,13+,"Documentary, Short",10,NaN,NaN,Ismail Fahmi Lubish,NaN,NaN,NaN,NaN
6,Cherrybelle: Chibi Chibi Burger,2012,13+,Drama,83,NaN,NaN,Akbar de Wighar,Cherly Yuliana Anggraini,Margareth Angelina,Brigitta Cynthia,Jessyca Stefani Auryn
7,RONG (Hole),2018,SU,"Short, Drama, Family",35,NaN,NaN,Sri Nugroho,NaN,NaN,NaN,NaN
8,Srimulat: Hil yang Mustahal - Babak Kedua,2022,SU,"Biography, Comedy, Drama",110,NaN,NaN,Fajar Nugros,NaN,NaN,NaN,NaN
9,Before You Eat,2022,18+,Documentary,96,NaN,NaN,Kasan Kurdi,NaN,NaN,NaN,NaN

In [84]:
# df['Rating'] = df['Rating'].astype('float')

df['Rating'] = df['Rating'].str.replace(',', '.').astype('float')

In [85]:
df.head(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
0,Kisah Tanah Jawa: Merapi,2019,18+,Horror,43,7.8,37,Faozan Rizal,Deva Mahenra,Joshua Suherman,Laura Basuki,Laura Theux
1,Negeri Dongeng,2017,SU,Documentary,98,8.9,8,Anggi Frisca,NaN,NaN,NaN,NaN
2,Workingman's Death,2005,13+,Documentary,122,7.9,"1,757",Michael Glawogger,NaN,NaN,NaN,NaN
3,Magic Hour,2015,18+,"Comedy, Drama",96,8.7,6,Asep Kusdinar,Dimas Anggara,Michelle Ziudith,Rizky Nazar,Nadya Arina
4,Jakarta Love Story,2015,13+,Romance,50,NaN,NaN,Vemmy Sagita,Irish Bella,Rezky Adhitya,Rionaldo Stockhorst,Mischa Chandrawinata
5,Homebound,2022,13+,"Documentary, Short",10,NaN,NaN,Ismail Fahmi Lubish,NaN,NaN,NaN,NaN
6,Cherrybelle: Chibi Chibi Burger,2012,13+,Drama,83,NaN,NaN,Akbar de Wighar,Cherly Yuliana Anggraini,Margareth Angelina,Brigitta Cynthia,Jessyca Stefani Auryn
7,RONG (Hole),2018,SU,"Short, Drama, Family",35,NaN,NaN,Sri Nugroho,NaN,NaN,NaN,NaN
8,Srimulat: Hil yang Mustahal - Babak Kedua,2022,SU,"Biography, Comedy, Drama",110,NaN,NaN,Fajar Nugros,NaN,NaN,NaN,NaN
9,Before You Eat,2022,18+,Documentary,96,NaN,NaN,Kasan Kurdi,NaN,NaN,NaN,NaN

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708 entries, 0 to 2707
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              2708 non-null   object
 1   Year               2708 non-null   int64
 2   Rated              2708 non-null   object
 3   Genre              2708 non-null   object
 4   Runtime (Minutes)  2708 non-null   int32
 5   Rating             1575 non-null   float64
 6   Votes              1575 non-null   object
 7   Director           2708 non-null   object
 8   Star 1             2470 non-null   object
 9   Star 2             2325 non-null   object
 10  Star 3             2140 non-null   object
 11  Star 4             1838 non-null   object
dtypes: float64(1), int32(1), int64(1), object(9)
memory usage: 243.4+ KB

In [97]:
# data['Rating'] = data['Rating'].replace(np.nan, 0)

df['Rating'] = df['Rating'].apply(lambda x: x if pd.notnull(x) else np.random.uniform(df['Rating'].min(), df['Rating'].max()))
df['Rating'] = df['Rating'].round(decimals = 1)

In [98]:
df.head(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
0,Kisah Tanah Jawa: Merapi,2019,18+,Horror,43,7.8,37,Faozan Rizal,Deva Mahenra,Joshua Suherman,Laura Basuki,Laura Theux
1,Negeri Dongeng,2017,SU,Documentary,98,8.9,8,Anggi Frisca,NaN,NaN,NaN,NaN
2,Workingman's Death,2005,13+,Documentary,122,7.9,"1,757",Michael Glawogger,NaN,NaN,NaN,NaN
3,Magic Hour,2015,18+,"Comedy, Drama",96,8.7,6,Asep Kusdinar,Dimas Anggara,Michelle Ziudith,Rizky Nazar,Nadya Arina
4,Jakarta Love Story,2015,13+,Romance,50,1.8,NaN,Vemmy Sagita,Irish Bella,Rezky Adhitya,Rionaldo Stockhorst,Mischa Chandrawinata
5,Homebound,2022,13+,"Documentary, Short",10,4.3,NaN,Ismail Fahmi Lubish,NaN,NaN,NaN,NaN
6,Cherrybelle: Chibi Chibi Burger,2012,13+,Drama,83,4.3,NaN,Akbar de Wighar,Cherly Yuliana Anggraini,Margareth Angelina,Brigitta Cynthia,Jessyca Stefani Auryn
7,RONG (Hole),2018,SU,"Short, Drama, Family",35,2.9,NaN,Sri Nugroho,NaN,NaN,NaN,NaN
8,Srimulat: Hil yang Mustahal - Babak Kedua,2022,SU,"Biography, Comedy, Drama",110,7.0,NaN,Fajar Nugros,NaN,NaN,NaN,NaN
9,Before You Eat,2022,18+,Documentary,96,4.6,NaN,Kasan Kurdi,NaN,NaN,NaN,NaN

In [99]:
df['Votes'] = df['Votes'].str.replace(',', '').astype('float')

In [100]:
df['Votes'] = df['Votes'].fillna(df['Votes'].interpolate())

In [101]:
df.head(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
0,Kisah Tanah Jawa: Merapi,2019,18+,Horror,43,7.8,37.000000,Faozan Rizal,Deva Mahenra,Joshua Suherman,Laura Basuki,Laura Theux
1,Negeri Dongeng,2017,SU,Documentary,98,8.9,8.000000,Anggi Frisca,NaN,NaN,NaN,NaN
2,Workingman's Death,2005,13+,Documentary,122,7.9,1757.000000,Michael Glawogger,NaN,NaN,NaN,NaN
3,Magic Hour,2015,18+,"Comedy, Drama",96,8.7,6.000000,Asep Kusdinar,Dimas Anggara,Michelle Ziudith,Rizky Nazar,Nadya Arina
4,Jakarta Love Story,2015,13+,Romance,50,1.8,6.285714,Vemmy Sagita,Irish Bella,Rezky Adhitya,Rionaldo Stockhorst,Mischa Chandrawinata
5,Homebound,2022,13+,"Documentary, Short",10,4.3,6.571429,Ismail Fahmi Lubish,NaN,NaN,NaN,NaN
6,Cherrybelle: Chibi Chibi Burger,2012,13+,Drama,83,4.3,6.857143,Akbar de Wighar,Cherly Yuliana Anggraini,Margareth Angelina,Brigitta Cynthia,Jessyca Stefani Auryn
7,RONG (Hole),2018,SU,"Short, Drama, Family",35,2.9,7.142857,Sri Nugroho,NaN,NaN,NaN,NaN
8,Srimulat: Hil yang Mustahal - Babak Kedua,2022,SU,"Biography, Comedy, Drama",110,7.0,7.428571,Fajar Nugros,NaN,NaN,NaN,NaN
9,Before You Eat,2022,18+,Documentary,96,4.6,7.714286,Kasan Kurdi,NaN,NaN,NaN,NaN

In [102]:
df['Votes'] = df['Votes'].astype('int')

In [103]:
df.tail(10)

,Title,Year,Rated,Genre,Runtime (Minutes),Rating,Votes,Director,Star 1,Star 2,Star 3,Star 4
2698,Arwah Tumbal Nyai the Trilogy: Part Arwah,2018,17+,Horror,104,3.7,59,Arie Azis,Zaskia Gotik,Shakti Arora,Lia Waode,Minati Atmanegara
2699,I Don't Believe You Died,2019,SU,"Horror, Mystery",85,4.9,100,Wimbadi J.P.,Zeeman Artaboga,Raditya Evandra,Kinaryosih,Farah Maudina
2700,Go Eight,2013,13+,"Action, Drama, Sport",122,7.2,141,Andibachtiar Yusuf,Zendhy Zain,Mathias Muchus,Ray Sahetapy,Tika Putri
2701,Silam,2018,17+,Horror,80,5.5,86,Jose Poernomo,Zidane Khalid,Surya Saputra,Wulan Guritno,Nova Eliza
2702,Bad Parenting,2022,13+,Drama,42,9.9,8,Martin Anugrah,Zidni Hakim,Assila Corina,Maddy Slinger,Nadila Ernesta
2703,Nariti: Romansa Danau Toba,2022,13+,Drama,85,3.4,10,Deden Bagaskara,Zoe Abbas Jackson,Bastian Steel,Paramitha Rusady,August Melasz
2704,Hompimpa,2021,D17+,"Horror, Thriller",87,6.5,12,Arie Azis,Zoe Abbas Jackson,Kenny Austin,Sebryan Yosvien,Sonia Alexa
2705,Moammar Emka's Jakarta Undercover,2017,21+,"Drama, Romance",129,7.1,121,Fajar Nugros,Zoya Amirin,Oka Antara,Ganindra Bimo,Edo Borne
2706,Dan Pulang,2019,13+,"Short, Drama",13,7.4,121,Daphne,Zulfa Maharani Putri,Oktavia Lisna,NaN,NaN
2707,Suporter Masuk Pesantren,2019,13+,"Comedy, Drama",84,8.6,121,Quraisy Mathar,Zulkifli Suardi,George Nataniel,Benyamin Yesnath,Ahmad Fauzan Fikri

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2708 entries, 0 to 2707
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              2708 non-null   object
 1   Year               2708 non-null   int64
 2   Rated              2708 non-null   object
 3   Genre              2708 non-null   object
 4   Runtime (Minutes)  2708 non-null   int32
 5   Rating             2708 non-null   float64
 6   Votes              2708 non-null   int32
 7   Director           2708 non-null   object
 8   Star 1             2470 non-null   object
 9   Star 2             2325 non-null   object
 10  Star 3             2140 non-null   object
 11  Star 4             1838 non-null   object
dtypes: float64(1), int32(2), int64(1), object(8)
memory usage: 232.8+ KB

In [104]:
output_file_path_excel = 'D:/Jupyter Notebook Project/Kaggle/IMDB Movies Indonesian/Data/Raw/imdb indonesia clean.xlsx'
output_file_path_csv = 'D:/Jupyter Notebook Project/Kaggle/IMDB Movies Indonesian/Data/Raw/imdb indonesia clean.csv'
df.to_excel(output_file_path_excel, index=False)
df.to_csv(output_file_path_csv, sep=',', index=False) #csv separator used = ','